
      fx_version "cerulean"
      games { 'gta5' }
      description 'This manifest was generated by fxmanifestmaker by LedAndris'
      version '1.0.0'
      author 'Jizzy boi'
      this_is_a_map "yes"

      